### ISSUE TITLE
Incorrect Typings

### ISSUE THREAD

**Issue by shafferchance-lulu** [MasatoMakino/threejs-interactive-object#36]
Instead of forking the library I opted to write my own pointer event manager. Along the way I hit a chain of type errors connected to the `Intersection<Object3D>` and viewport. I can put up a PR with the fixes.

`getMousePosition` from `ViewPortUtil.ts` should have viewport as optional per your check.

`checkTarget` detects that `target.parent` can be null which makes sense. To mitigate this I added a coalescence check at the beginning of the conditional.

**Comment by shafferchance-lulu** [comment]
I'm also curious why you have not published this as a package to NPM, any particular reason why?

**Comment by MasatoMakino** [comment]
@shafferchance-lulu 

Thanks for your comment. I welcome your Pull Requests.

> getMousePosition from ViewPortUtil.ts should have viewport as optional per your check.

> checkTarget detects that target.parent can be null which makes sense. To mitigate this I added a coalescence check at the beginning of the conditional.

I request that you create separate PRs for these two issues. 

> I'm also curious why you have not published this as a package to NPM, any particular reason why?

I am not sure if there is enough demand for this library to make it public on npm. Publishing a library in npm incurs maintenance work costs.

**Comment by MasatoMakino** [comment]
@shafferchance-lulu

Incorrect type issue was resolved by a Pull Request. To prevent it from happening again, I enabled "strictNullChecks" in the TypeScript config.

This package was also published in NPM.

If there are no problems, I will close this issue.
